version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    restart: always
    env_file:
      - .env
    ports:
      - "4002:4002"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
